// <auto-generated />
using System;
using Calorie_Journal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Calorie_Journal.Migrations.Intake
{
    [DbContext(typeof(IntakeContext))]
    [Migration("20190629044625_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Calorie_Journal.Models.Food", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Calories");

                    b.Property<decimal>("Carbs");

                    b.Property<string>("Name");

                    b.Property<decimal>("Serving");

                    b.HasKey("ID");

                    b.ToTable("Food");
                });

            modelBuilder.Entity("Calorie_Journal.Models.Intake", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FoodID");

                    b.Property<decimal>("Quantity");

                    b.Property<DateTime>("Time");

                    b.HasKey("ID");

                    b.HasIndex("FoodID");

                    b.ToTable("Intake");
                });

            modelBuilder.Entity("Calorie_Journal.Models.Intake", b =>
                {
                    b.HasOne("Calorie_Journal.Models.Food", "FoodEntry")
                        .WithMany()
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
